const projects = [
  { number: '01', url: 'https://github.com/cwcasado/Algoritmos_sort', tag: 'ALGORITMOS', title: 'Algoritmos de ordenação', description: 'Trabalho de apresentação de nove algoritmos de ordenação. Um estudo em Python sobre diferentes formas de organizar dados.', tech: 'Python · Ordenação', symbol: '◎', style: 'map' },
  { number: '02', url: 'https://github.com/cwcasado/algoritmos-segundo-per-odo-lista-4', tag: 'LÓGICA & PRÁTICA', title: 'Funções recursivas', description: 'Exercícios de funções recursivas em Python. Explorando a resolução de problemas a partir de versões menores do mesmo problema.', tech: 'Python · Recursividade', symbol: '>_', style: 'python' },
  { number: '03', url: 'https://github.com/cwcasado/Exerc-cio-algoritmo', tag: 'FUNDAMENTOS', title: 'Explorando matrizes', description: 'Exercícios em Python para aprender sobre matrizes. Praticando a organização de dados e desenvolvendo o raciocínio lógico.', tech: 'Python · Matrizes', symbol: '{ }', style: 'cpp' },
]
export default function Projetos() {
  return <section id="projetos" className="section projects"><div className="section-heading"><div><p className="eyebrow">02 — PROJETOS & HABILIDADES</p><h2>Da teoria à prática.</h2></div><p>Um pouco do que estou<br />estudando e desenvolvendo.</p></div><div className="cards-container">{projects.map(project => <article className="card" key={project.number}><div className={`card-art ${project.style}`} aria-hidden="true"><span>{project.symbol}</span><small>{project.number}</small></div><div className="card-copy"><p className="eyebrow">{project.tag}</p><h3>{project.title}</h3><p>{project.description}</p><div className="card-tech">{project.tech}</div><a className="project-link" href={project.url} target="_blank" rel="noreferrer">Ver repositório ↗<span className="sr-only">: {project.title}</span></a></div></article>)}</div><aside className="audio-panel"><div><p className="eyebrow">APERTE O PLAY</p><h3>Uma pausa entre linhas de código.</h3><p>Uma breve sequência instrumental original para acompanhar este espaço.</p></div><audio controls preload="metadata" aria-label="Ouvir sequência instrumental original"><source src="/pausa.wav" type="audio/wav" />Seu navegador não suporta áudio. <a href="/pausa.wav">Baixe a faixa.</a></audio></aside></section>
}

